apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: batch-service
  template:
    metadata:
      labels:
        app: batch-service
    spec:
      containers:
        - name: batch-service
          image: your-docker-image
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_REDIS_HOST
              value: redis
            - name: SPRING_REDIS_PORT
              value: "6379"
